In [47]:
import numpy as np

In [48]:
b = np.array(1, 1, 3, 4, 5, dtype=float)

ValueError: only 2 non-keyword arguments accepted

In [49]:
c=np.array([False,True,True])
c
type(c)

numpy.ndarray

In [50]:
f=np.arange(1,2,0.5,dtype=float)
f
type(f)

numpy.ndarray

In [51]:
b = np.array([1, 2, 6, 4, 5], dtype=float)
b
type(b)

numpy.ndarray

In [52]:
a = np.array([6, 5, -5])
b = np.array([-1, 4, 7])


In [53]:
np.linalg.norm(a, ord=2) - np.linalg.norm(b, ord=2)

1.1495800908597431

In [54]:
import scipy.spatial
scipy.spatial.distance.cdist(a[:, np.newaxis], b[:, np.newaxis], metric='euclidean')

array([[  7.,   2.,   1.],
       [  6.,   1.,   2.],
       [  4.,   9.,  12.]])

In [55]:
scipy.spatial.distance.cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')

array([[ 13.92838828]])

In [56]:
scipy.spatial.distance.cdist(b, a, metric='euclidean')

ValueError: XA must be a 2-dimensional array.

In [67]:
a = np.array([0, -6, 11])
b = np.array([3, 4, 2])

In [58]:
 a = np.array([8, 4, -1, 0, 0])

In [59]:
a = a[:, np.newaxis]
a

array([[ 8],
       [ 4],
       [-1],
       [ 0],
       [ 0]])

In [60]:
a = a.reshape((1, 5))
a

array([[ 8,  4, -1,  0,  0]])

In [61]:
a = a.reshape((5, 1))
a

array([[ 8],
       [ 4],
       [-1],
       [ 0],
       [ 0]])

In [62]:
a = a[np.newaxis, :]
a

array([[[ 8],
        [ 4],
        [-1],
        [ 0],
        [ 0]]])

In [68]:
np.dot(a, b)

-2

In [69]:
np.dot(a, b) / np.linalg.norm(a) / np.linalg.norm(b)

-0.029640202781176964

In [70]:
b.dot(a)

-2

In [66]:
a * b

array([[[24, 32, 16],
        [12, 16,  8],
        [-3, -4, -2],
        [ 0,  0,  0],
        [ 0,  0,  0]]])