In [3]:
import numpy as np
a = np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])
a

ValueError: only 2 non-keyword arguments accepted

In [4]:
b = np.eye(2, 3)
b

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [5]:
c = np.eye((4, 5))
c

TypeError: an integer is required

In [6]:
d = np.ones((10, 10))
d

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [7]:
e = np.arange(1, 13, 2).reshape((3, 2))
e

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [13]:
a = np.eye(4, 4)
a

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [11]:
a[[0, 3], [1, 3]]

array([ 0.,  1.])

In [14]:
np.linalg.det(a)

1.0

In [15]:
np.det(a)

AttributeError: 'module' object has no attribute 'det'

In [16]:
np.linalg.inv(a)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [17]:
np.transpose(a)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [18]:
np.linalg.eig(a)

(array([ 1.,  1.,  1.,  1.]), array([[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]]))

In [19]:
np.linalg.solve(a)

TypeError: solve() takes exactly 2 arguments (1 given)

In [20]:
np.eig(a)

AttributeError: 'module' object has no attribute 'eig'

In [21]:
np.linalg.matrix_rank(a)

4

In [22]:
np.solve(a)

AttributeError: 'module' object has no attribute 'solve'